---
HOSTS:
  centos-8-kubevirt:
    platform: el-8-x86_64
    hypervisor: kubevirt
    # VM-specific configuration
    kubevirt_vm_image: docker://quay.io/kubevirt/centos-stream8-container-disk-demo
    kubevirt_network_mode: port-forward
    kubevirt_ssh_key: ~/.ssh/id_rsa.pub
    kubevirt_cpus: 2
    kubevirt_memory: 4Gi
    # Beaker-specific configuration
    user: centos
    ssh:
      auth_methods:
        - publickey

  ubuntu-20-kubevirt:
    platform: ubuntu-20.04-x86_64
    hypervisor: kubevirt
    # Use a PVC as the VM image
    kubevirt_vm_image: pvc:ubuntu-20-04-cloud-image
    kubevirt_network_mode: nodeport
    kubevirt_ssh_key: ~/.ssh/id_rsa.pub
    kubevirt_cpus: 1
    kubevirt_memory: 2Gi
    user: ubuntu
    ssh:
      auth_methods:
        - publickey

  fedora-35-kubevirt:
    platform: fedora-35-x86_64
    hypervisor: kubevirt
    # Use Multus external networking
    kubevirt_vm_image: docker://quay.io/kubevirt/fedora-cloud-container-disk-demo
    kubevirt_network_mode: multus
    kubevirt_ssh_key: ~/.ssh/id_rsa.pub
    kubevirt_cpus: 2
    kubevirt_memory: 2Gi
    networks:
      - name: ext0
        multus_network_name: my-bridge-network
    user: fedora
    ssh:
      auth_methods:
        - publickey

CONFIG:
  # Global KubeVirt configuration, use the KUBECONFIG env var or default path
  kubeconfig: <%= ENV.fetch('KUBECONFIG', '~/.kube/config') %>
  kubecontext: my-cluster  # optional
  namespace: beaker-tests  # required - namespace for all VMs
  
  # Global SSH configuration
  ssh:
    password: beaker
    auth_methods:
      - publickey
      - password
  
  # Global timeout settings
  timeout: 300
  
  # Test configuration
  log_level: verbose
  color: true
